server:
  port: 9090

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8084
              predicates:
                - Path=/users/**
                - Header=name, aya
              filters:
                - AddRequestHeader=X-Request-Gateway, Gateway-Test
                - AddResponseHeader=X-Response-Gateway, Gateway-Response

            - id: product-service
              uri: http://localhost:8086
              predicates:
                - Path=/products/**
              filters:
                - AddRequestHeader=X-Request-Gateway, Gateway-Product
                - AddResponseHeader=X-Response-Gateway, Gateway-Response-Product
		- name: RequestRateLimiter
                  args:  
                    redis-rate-limiter.replenishRate: 1
                    redis-rate-limiter.burstCapacity: 2
                    key-resolver: "#{@ipKeyResolver}"

          default-filters:
            - AddRequestHeader=X-Gateway-Global, GlobalHeader

    redis:
      host: localhost
      port: 6379

spring.cloud.gateway.server.webflux.filter.request-rate-limiter.enabled: true